apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: kube-registry.kube-system.svc.cluster.local:31000/miguelgrinberg/easy-etcd
        ports:
        - containerPort: 2379
        - containerPort: 2380
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  type: NodePort
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    app: etcd
