apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
type: Opaque
data:
  # echo -n "admin123" | base64
  postgres-password: "YWRtaW4xMjM="
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  name: postgres-replicas
  labels:
    app: postgres-replicas
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: postgres-replicas
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: danieldent/postgres-replication
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data/pgdata
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: postgres-password
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        #- name: REPLICATE_FROM
        #  value: postgres-0.postgres.default.svc.cluster.local
        readinessProbe:
          exec:
            command: [ "/usr/bin/psql", "-U", "postgres", "-c", "select 1;" ]
          initialDelaySeconds: 2
          periodSeconds: 2
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replicas
spec:
  serviceName: "postgres-replicas"
  replicas: 2
  selector:
    matchLabels:
      app: postgres-replicas
  template:
    metadata:
      labels:
        app: postgres-replicas
    spec:
      containers:
      - name: postgres-replicas
        image: danieldent/postgres-replication
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata-replicas
          mountPath: /var/lib/postgresql/data/pgdata
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: postgres-password
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: REPLICATE_FROM
          value: postgres-0.postgres.default.svc.cluster.local
        readinessProbe:
          exec:
            command: [ "/usr/bin/psql", "-U", "postgres", "-c", "select 1;" ]
          initialDelaySeconds: 2
          periodSeconds: 2
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: pgdata-replicas
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi




  
